dist: trusty
sudo: false

language: node_js
node_js:
  - '14.17.5'

addons:
  chrome: stable
  apt:
    update: true

cache:
  directories:
    - ./node_modules

script:
  - cd app
  - npm install
  - npm test
  - cd ..
  - cd angular
  - npm install
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

services:
  - mongodb