version: 2.1
orbs:
  node: circleci/node@4.7
  
jobs:
  nodejs:
    working_directory: ~/linea-de-tiempo/app
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mongo:latest'

    steps:
      - checkout:
          path: ~/linea-de-tiempo
      - run:
          command: |
            npm install
            npm test
  angulartest:
    working_directory: ~/linea-de-tiempo/angular
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout:
          path: ~/linea-de-tiempo
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
workflows:
  sample: 
    jobs:
      - nodejs
      - angulartest
