# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  common: okode/common@2.0.11

jobs:
  angulartest:
    executor:
      name: common/node
      feature: '-browsers'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Building
          command: npm run build --prod
      - common/chrome-upgrade
      - run:
          name: Running unit tests
          command: npm run test
            
#jobs:
 # nodejs:
  #  working_directory: ~/linea-de-tiempo/app
   # docker:
    #  - image: 'circleci/node:latest'
     # - image: 'circleci/mongo:latest'

#    steps:
 #     - checkout:
  #        path: ~/linea-de-tiempo
   #   - run:
    #      command: |
     #       npm install
      #      npm test
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - angulartest
