@token = 
@url = http://localhost:4000

### Test

GET {{url}}

### Get all
GET {{url}}/timeline/

### Get by id
GET {{url}}/timeline/61524dcb3ee310266b80c599

### Create time line
POST {{url}}/timeline/
Content-Type: application/json

{
    "title" : "La vida de Maria Juana",
    "category" : "BIOGRAPHY",
    "entries": [
        {
            "title": "title del punto",
            "text": "description",
            "date": {
                "year": 1922, 
                "month": 1
            }
        },
        {
            "title": "title del punto 2",
            "text": "description",
            "date": {
                "year": 1922, 
                "month": 2
            }
        }
    ]
}

### Search by category HISTORY

GET {{url}}/timeline/category/HISTORY/

### Search by category GEOGRAPHY

GET {{url}}/timeline/category/GEOGRAPHY/

### Search by category BIOGRAPHY

GET {{url}}/timeline/category/BIOGRAPHY/

### Modify time line
PUT {{url}}/timeline/61524dcb3ee310266b80c599
Content-Type: application/json

{
    "title": "linea modificada",
    "category": "GEOGRAPHY",
    "entries": [{
        "title": "title ",
        "text": "descripcion",
        "date": { 
            "year": 1922
        }
    },{
        "title": "other title",
        "text": "Hi",
        "date": { 
            "year": 2, 
            "ad": false
        }
    }]
}

### Log in
POST {{url}}/user/login
Content-Type: application/json

{
    "email": "some@mail.com",
    "password": "abcde1234"
}

### Sign Up
POST {{url}}/user/register
Content-Type: application/json

{
    "email": "some",
    "password": "abcde12345",
    "name": "nombre"
}