@token = 
@url = http://localhost:4000

### Test

GET {{url}}

### Get all
GET {{url}}/timeline/

### Get by id
GET {{url}}/timeline/616f59cf005ee6b548acbef6

### Create time line
POST {{url}}/timeline/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzNDU5NTEwOCwiZXhwIjoxNjM0NjgxNTA4fQ.YmivFnjMjmTU-lOW_02JOX6eUPdlSq_UximseRPsc_g

{
    "title" : "La vida de tu vieja",
    "category" : "BIOGRAPHY",
    "entries": [
        {
            "title": "title del punto",
            "text": "description",
            "date": {
                "year": 1922, 
                "month": 1
            }
        },
        {
            "title": "title del punto 2",
            "text": "description",
            "date": {
                "year": 1922, 
                "month": 2
            }
        }
    ],
    "collaborators": ["admin@admin.com"]
}

### Search by category HISTORY

GET {{url}}/timeline/category/HISTORY/

### Search by category GEOGRAPHY

GET {{url}}/timeline/category/GEOGRAPHY/

### Search by category BIOGRAPHY

GET {{url}}/timeline/category/BIOGRAPHY/

### Modify time line
PUT {{url}}/timeline/61524dcb3ee310266b80c599
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWVAbWFpbC5jb20iLCJpYXQiOjE2MzM3MzQwOTMsImV4cCI6MTYzMzgyMDQ5M30.3bIwWJWO2g1MqwZnrlGj0vWhDP8kK9zlCqSM0XBaqy4

{
    "title": "linea modificada",
    "category": "GEOGRAPHY",
    "entries": [{
        "title": "title ",
        "text": "descripcion",
        "date": { 
            "year": 1922
        }
    },{
        "title": "other title",
        "text": "Hi",
        "date": { 
            "year": 2, 
            "ad": false
        }
    }]
}

### Log in
POST {{url}}/user/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin1"
}

### Sign Up
POST {{url}}/user/register
Content-Type: application/json

{
    "email": "some@mail.com",
    "password": "abcde12345",
    "name": "nombre"
}


### Get examples
GET {{url}}/timeline/example

### My timelines 
GET {{url}}/timeline/mytimelines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzNDU5NTEwOCwiZXhwIjoxNjM0NjgxNTA4fQ.YmivFnjMjmTU-lOW_02JOX6eUPdlSq_UximseRPsc_g

### Publish
POST {{url}}/timeline/616df8abc833fa9ce3197a77/publish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzNDU5NTEwOCwiZXhwIjoxNjM0NjgxNTA4fQ.YmivFnjMjmTU-lOW_02JOX6eUPdlSq_UximseRPsc_g


### Unpublish
POST {{url}}/timeline/616df8abc833fa9ce3197a77/unpublish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzNDU5NTEwOCwiZXhwIjoxNjM0NjgxNTA4fQ.YmivFnjMjmTU-lOW_02JOX6eUPdlSq_UximseRPsc_g
