@token = 
@url = http://localhost:4000

### Prueba

GET {{url}}

### Obtener lineas de tiempo
GET {{url}}/lineaDeTiempo/

### Obtener lineas de tiempo por id
GET {{url}}/lineaDeTiempo/61453249933b3120fb146576

### Crear Linea de tiempo
POST {{url}}/lineaDeTiempo/
Content-Type: application/json

{
    "titulo" : "La vida de Maria Juana",
    "categoria" : "BIOGRAFIA",
    "puntos": [
        {
            "titulo": "titulo del punto",
            "texto": "descripcion",
            "fecha": "2021-09-13"
        },
        {
            "titulo": "titulo del punto 2",
            "texto": "descripcion",
            "fecha": "2021-09-29"
        }
    ]
}

### Buscar Linea de Tiempo por categoria HISTORIA

GET {{url}}/lineaDeTiempo/categoria/HISTORIA/

### Buscar Linea de Tiempo por categoria GEOGRAFIA

GET {{url}}/lineaDeTiempo/categoria/GEOGRAFIA/

### Buscar Linea de Tiempo por categoria BIOGRAFIA

GET {{url}}/lineaDeTiempo/categoria/BIOGRAFIA/
